server:
  port: 8082

spring:
  application:
    name: cloudprovider
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: daiwenxiang

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7776/eureka

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl